import streamlit as st

st.title("Streamlit Widgets Demo")
st.header("Demonstration of Various Widgets")
st.subheader("1. Button Widget")
if st.button("Click Me"):
    st.write("Button Clicked!")
st.subheader("2. Checkbox Widget")
if st.checkbox("Check Me"):
    st.write("Checkbox Selected!")
st.subheader("3. Radio Button Widget")
option = st.radio("Choose an option:", ['Option 1', 'Option 2', 'Option 3'])
st.write(f"You selected: {option}")
st.subheader("4. Selectbox Widget")
selection = st.selectbox("Pick a number:", [10, 20, 30,
    40, 50])
st.write(f"You picked: {selection}")
st.subheader("5. Multiselect Widget")
choices = st.multiselect("Select multiple options:", 
    ['Apple', 'Banana', 'Cherry', 'Date'], default=['Banana', 'Date'])
st.write(f"You selected: {choices}")
st.subheader("6. Slider Widget")
slider_value = st.slider("Select a value:", 0, 100, 25)
st.write(f"Slider value: {slider_value}")
st.subheader("7. Text Input Widget")
text_input = st.text_input("Enter some text:")
st.write(f"You entered: {text_input}")
st.subheader("8. Text Area Widget")
text_area = st.text_area("Enter a longer text:")
st.write(f"You wrote: {text_area}")
st.subheader("9. Date Input Widget")
date = st.date_input("Select a date:")
st.write(f"You selected: {date}")
st.subheader("10. Time Input Widget")
time = st.time_input("Select a time:")
st.write(f"You selected: {time}")
st.subheader("11. File Uploader Widget")
uploaded_file = st.file_uploader("Upload a file:")
if uploaded_file is not None:
    st.write(f"File uploaded: {uploaded_file.name}")
st.subheader("12. Color Picker Widget")
color = st.color_picker("Pick a color:", "#00f900")
st.write(f"You picked: {color}")
st.subheader("13. Sidebar Widget")
sidebar_option = st.sidebar.selectbox("Sidebar Selectbox:", ['A', 'B', 'C'])
st.sidebar.write(f"You selected: {sidebar_option}")

st.subheader("14. Progress Bar Widget")
import time
progress_bar = st.progress(0)
for percent_complete in range(100):
    time.sleep(0.01)
    progress_bar.progress(percent_complete + 1)
st.write("Progress complete!")
st.subheader("15. Spinner Widget")
with st.spinner("Loading..."):
    time.sleep(2)

st.success("Loading complete!")
st.subheader("16. Balloons Animation")
st.balloons()
st.subheader("17. Help Widget")
st.help(st.slider)
st.subheader("18. Markdown Widget")
st.markdown("### This is a markdown header\n- Item 1\n- Item 2\n- Item 3")
st.subheader("19. Code Widget")
st.code("def hello_world():\n    print('Hello, world!')", language='python')
st.subheader("20. Latex Widget")
st.latex(r''' e^{i\pi} + 1 = 0 ''')
st.subheader("21. JSON Widget")
st.json({'name': 'Streamlit', 'type': 'library', 'language': 'Python'})
st.subheader("22. Metric Widget")
st.metric(label="Temperature", value="70 °F", delta="+1.2 °F")
