tup = ('AAple', 4, 7.43, True, 43, 'Koco', 4)
numTupe = (98, 43, 65, 112, 50, 21, 99, 43)
print('Mixed tuple - ',tup)
print('Number tuple - ',numTupe)
print('tup.count(43) - ',tup.count(43))
print('tup.index(True) - ',tup.index(True))
print('max(numTupe) - ',max(numTupe))
print('min(numTupe) - ',min(numTupe))
print('len(numTupe) - ',len(numTupe))
